version: "3.9"
services:
  grpcserver:
    build: ./server
    ports:
      - "50052:50051"
    networks:
      - grpctuiter

  grpcclient:
    build: ./cliente
    environment:
      - CLIENT_HOST=:5000
      - SERVER_HOST=grpcserver:50051
      - NAME=instanciagrpc
    ports:
      - "5001:5000"
    networks:
      - grpctuiter
  node:
    restart: on-failure
    build: ./nodejsapp
    depends_on: 
      - mongo
    ports:
      - 3000:3000
    networks:
      - grpctuiter
    volumes:
      - ./:/code
  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - grpctuiter
    volumes:
      - mongodb:/data/db
volumes:
 mongodb:
  

networks:
  grpctuiter:
    driver: "bridge"